/* tslint:disable */
/* eslint-disable */
/**
 * Survivor Fantasy League - OpenAPI 3.0.3
 * This is the Survivor Fantasy League Spec for API's
 *
 * OpenAPI spec version: 1.0.11
 * Contact: pklein111697@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Profile } from './profile';
 /**
 * 
 *
 * @export
 * @interface Account
 */
export interface Account extends Profile {

    /**
     * Email of user
     *
     * @type {string}
     * @memberof Account
     */
    email: string;

    /**
     * User Id of user
     *
     * @type {string}
     * @memberof Account
     */
    userId: string;

    /**
     * User role ADMIN or USER
     *
     * @type {string}
     * @memberof Account
     */
    userRole: AccountUserRoleEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum AccountUserRoleEnum {
    ADMIN = 'ADMIN',
    USER = 'USER'
}

