/* tslint:disable */
/* eslint-disable */
/**
 * Survivor Fantasy League - OpenAPI 3.0.3
 * This is the Survivor Fantasy League Spec for API's
 *
 * OpenAPI spec version: 1.0.11
 * Contact: pklein111697@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { LeagueSurvey } from './league-survey';
import { PickAndChoice } from './pick-and-choice';
import { SurveyAvailabilityStatus } from './survey-availability-status';
import { SurveySubmissionStatus } from './survey-submission-status';
 /**
 * 
 *
 * @export
 * @interface CompletedLeagueSurvey
 */
export interface CompletedLeagueSurvey extends LeagueSurvey {

    /**
     * The ID of the profile submitting the survey
     *
     * @type {string}
     * @memberof CompletedLeagueSurvey
     */
    profileId: string;

    /**
     * The ID of the league profile submitting the survey
     *
     * @type {string}
     * @memberof CompletedLeagueSurvey
     */
    leagueProfileId: string;

    /**
     * @type {Array<PickAndChoice>}
     * @memberof CompletedLeagueSurvey
     */
    picks: Array<PickAndChoice>;
}
