/* tslint:disable */
/* eslint-disable */
/**
 * Survivor Fantasy League - OpenAPI 3.0.3
 * This is the Survivor Fantasy League Spec for API's
 *
 * OpenAPI spec version: 1.0.11
 * Contact: pklein111697@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Episode } from './episode';
import { LeagueSurvey } from './league-survey';
import { PickSelection } from './pick-selection';
import { SurveyAvailabilityStatus } from './survey-availability-status';
 /**
 * 
 *
 * @export
 * @interface CompletedLeagueSurvey
 */
export interface CompletedLeagueSurvey extends LeagueSurvey {

    /**
     * @type {Array<PickSelection>}
     * @memberof CompletedLeagueSurvey
     */
    pickSelections: Array<PickSelection>;

    /**
     * The ID of the league the survey is submitted in
     *
     * @type {string}
     * @memberof CompletedLeagueSurvey
     */
    leagueId: string;

    /**
     * The ID of the profile submitting the survey
     *
     * @type {string}
     * @memberof CompletedLeagueSurvey
     */
    profileId: string;
}
