/* tslint:disable */
/* eslint-disable */
/**
 * Survivor Fantasy League - OpenAPI 3.0.3
 * This is the Survivor Fantasy League Spec for API's
 *
 * OpenAPI spec version: 1.0.11
 * Contact: pklein111697@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { LeagueMemberSurvey } from './league-member-survey';
import { PickAndChoice } from './pick-and-choice';
import { SurveySubmissionStatus } from './survey-submission-status';
 /**
 * 
 *
 * @export
 * @interface CompletedLeagueMemberSurvey
 */
export interface CompletedLeagueMemberSurvey extends LeagueMemberSurvey {

    /**
     * @type {Array<PickAndChoice>}
     * @memberof CompletedLeagueMemberSurvey
     */
    picks: Array<PickAndChoice>;
}
