/* tslint:disable */
/* eslint-disable */
/**
 * Survivor Fantasy League - OpenAPI 3.0.3
 * This is the Survivor Fantasy League Spec for API's
 *
 * OpenAPI spec version: 1.0.11
 * Contact: pklein111697@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateLeagueRequestBody
 */
export interface CreateLeagueRequestBody {

    /**
     * The name of the league
     *
     * @type {string}
     * @memberof CreateLeagueRequestBody
     * @example Corner By The Bookshelf
     */
    name: string;

    /**
     * The ID of the season the league belongs to
     *
     * @type {number}
     * @memberof CreateLeagueRequestBody
     * @example 47
     */
    seasonId: number;

    /**
     * The profileId of the user creating the league
     *
     * @type {string}
     * @memberof CreateLeagueRequestBody
     * @example 49e27bd8-dc24-4159-9630-e989025bf8fd
     */
    profileId: string;
}
