/* tslint:disable */
/* eslint-disable */
/**
 * Survivor Fantasy League - OpenAPI 3.0.3
 * This is the Survivor Fantasy League Spec for API's
 *
 * OpenAPI spec version: 1.0.11
 * Contact: pklein111697@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CompletedLeagueSurvey } from './completed-league-survey';
import { LeagueSurvey } from './league-survey';
 /**
 * 
 *
 * @export
 * @interface GetLeagueSurveyResponseData
 */
export interface GetLeagueSurveyResponseData {

    /**
     * @type {LeagueSurvey | CompletedLeagueSurvey}
     * @memberof GetLeagueSurveyResponseData
     */
    leagueSurvey: LeagueSurvey | CompletedLeagueSurvey;

    /**
     * Indicates if the survey is completed. If true, then leagueSurvey should be CompletedLeagueSurvey and if not then LeagueSurvey
     *
     * @type {boolean}
     * @memberof GetLeagueSurveyResponseData
     * @example true
     */
    isCompleted: boolean;
}
