/* tslint:disable */
/* eslint-disable */
/**
 * Survivor Fantasy League - OpenAPI 3.0.3
 * This is the Survivor Fantasy League Spec for API's
 *
 * OpenAPI spec version: 1.0.11
 * Contact: pklein111697@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CompletedLeagueMemberSurvey } from './completed-league-member-survey';
import { LeagueMemberSurvey } from './league-member-survey';
 /**
 * 
 *
 * @export
 * @interface GetLeagueMemberSurveyResponseData
 */
export interface GetLeagueMemberSurveyResponseData {

    /**
     * @type {LeagueMemberSurvey | CompletedLeagueMemberSurvey}
     * @memberof GetLeagueMemberSurveyResponseData
     */
    leagueSurvey: LeagueMemberSurvey | CompletedLeagueMemberSurvey;

    /**
     * Indicates if the survey is completed. If true, then leagueSurvey should be CompletedLeagueSurvey and if not then LeagueSurvey
     *
     * @type {boolean}
     * @memberof GetLeagueMemberSurveyResponseData
     * @example true
     */
    isCompleted: boolean;
}
