/* tslint:disable */
/* eslint-disable */
/**
 * Survivor Fantasy League - OpenAPI 3.0.3
 * This is the Survivor Fantasy League Spec for API's
 *
 * OpenAPI spec version: 1.0.11
 * Contact: pklein111697@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { PickIdAndPlayerChoice } from './pick-id-and-player-choice';
 /**
 * 
 *
 * @export
 * @interface SubmitSurveyRequestBody
 */
export interface SubmitSurveyRequestBody {

    /**
     * The ID of the episode.
     *
     * @type {string}
     * @memberof SubmitSurveyRequestBody
     */
    episodeId: string;

    /**
     * The ID of the league survey.
     *
     * @type {string}
     * @memberof SubmitSurveyRequestBody
     */
    leagueSurveyId: string;

    /**
     * The ID of the survey.
     *
     * @type {string}
     * @memberof SubmitSurveyRequestBody
     */
    surveyId: string;

    /**
     * The ID of the league.
     *
     * @type {string}
     * @memberof SubmitSurveyRequestBody
     */
    leagueId: string;

    /**
     * The ID of the profile.
     *
     * @type {string}
     * @memberof SubmitSurveyRequestBody
     */
    profileId: string;

    /**
     * @type {Array<PickIdAndPlayerChoice>}
     * @memberof SubmitSurveyRequestBody
     */
    picksWithChoice: Array<PickIdAndPlayerChoice>;
}
