/* tslint:disable */
/* eslint-disable */
/**
 * Survivor Fantasy League - OpenAPI 3.0.3
 * This is the Survivor Fantasy League Spec for API's
 *
 * OpenAPI spec version: 1.0.11
 * Contact: pklein111697@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { SurvivorEliminationType } from './survivor-elimination-type';
 /**
 * 
 *
 * @export
 * @interface SurvivorFinishStatus
 */
export interface SurvivorFinishStatus {

    /**
     * Whether the survivor's torch was snuffed
     *
     * @type {boolean}
     * @memberof SurvivorFinishStatus
     * @example false
     */
    isTorchSnuffed?: boolean;

    /**
     * The placement of the survivor in the seaosn. Last place is 18th
     *
     * @type {number}
     * @memberof SurvivorFinishStatus
     */
    placement?: number | null;

    /**
     * The placement of the survivor in the season. Last place is 18th
     *
     * @type {string}
     * @memberof SurvivorFinishStatus
     * @example 18th
     */
    placementText?: string | null;

    /**
     * The day the survivor was eliminated
     *
     * @type {number}
     * @memberof SurvivorFinishStatus
     * @example 12
     */
    dayEliminated?: number | null;

    /**
     * The placement of the jury member. 1st through 8th jury members with 1st being the first one voted out to the jury
     *
     * @type {number}
     * @memberof SurvivorFinishStatus
     * @example 3
     */
    juryPlacement?: number | null;

    /**
     * The placement of the jury member. 1st through 8th jury members with 1st being the first one voted out to the jury
     *
     * @type {string}
     * @memberof SurvivorFinishStatus
     * @example 3rd
     */
    juryPlacementText?: string | null;

    /**
     * The episode id the survivor was eliminated in
     *
     * @type {string}
     * @memberof SurvivorFinishStatus
     * @example 5
     */
    episodeIdEliminated?: string | null;

    /**
     * @type {SurvivorEliminationType}
     * @memberof SurvivorFinishStatus
     */
    eliminationType?: SurvivorEliminationType;
}
