/* tslint:disable */
/* eslint-disable */
/**
 * Survivor Fantasy League - OpenAPI 3.0.3
 * This is the Survivor Fantasy League Spec for API's
 *
 * OpenAPI spec version: 1.0.11
 * Contact: pklein111697@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TribeMembership } from './tribe-membership';
 /**
 * 
 *
 * @export
 * @interface TribeMemberStatusOnEpisode
 */
export interface TribeMemberStatusOnEpisode {

    /**
     * The tribe's unique identifier
     *
     * @type {string}
     * @memberof TribeMemberStatusOnEpisode
     * @example 49e27bd8-dc24-4159-9630-e989025bf8fd
     */
    tribeId: string;

    /**
     * @type {TribeMembership}
     * @memberof TribeMemberStatusOnEpisode
     */
    tribeMembersEpisodeStart: TribeMembership;

    /**
     * @type {TribeMembership}
     * @memberof TribeMemberStatusOnEpisode
     */
    tribeMembersBeforeElimination: TribeMembership;

    /**
     * @type {TribeMembership}
     * @memberof TribeMemberStatusOnEpisode
     */
    tribeMembersAtEndOfEpisode: TribeMembership;
}
