/* tslint:disable */
/* eslint-disable */
/**
 * Survivor Fantasy League - OpenAPI 3.0.3
 * This is the Survivor Fantasy League Spec for API's
 *
 * OpenAPI spec version: 1.0.11
 * Contact: pklein111697@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ApiResponse
 */
export interface ApiResponse {

    /**
     * @type {boolean}
     * @memberof ApiResponse
     * @example true
     */
    success: boolean;

    /**
     * @type {string}
     * @memberof ApiResponse
     * @example Operation completed successfully.
     */
    message: string;

    /**
     * @type {number}
     * @memberof ApiResponse
     * @example 200
     */
    statusCode: number;

    /**
     * @type {string}
     * @memberof ApiResponse
     * @example An error occurred.
     */
    error?: string | null;
}
