/* tslint:disable */
/* eslint-disable */
/**
 * Survivor Fantasy League - OpenAPI 3.0.3
 * This is the Survivor Fantasy League Spec for API's
 *
 * OpenAPI spec version: 1.0.11
 * Contact: pklein111697@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateTribeRequestBody
 */
export interface CreateTribeRequestBody {

    /**
     * The tribe's name
     *
     * @type {string}
     * @memberof CreateTribeRequestBody
     * @example Luzon
     */
    name: string;

    /**
     * The season's unique identifier
     *
     * @type {number}
     * @memberof CreateTribeRequestBody
     * @example 1
     */
    seasonId: number;

    /**
     * Whether the tribe is a merge tribe
     *
     * @type {boolean}
     * @memberof CreateTribeRequestBody
     * @example false
     */
    isMergeTribe: boolean;

    /**
     * The episode the tribe started in
     *
     * @type {number}
     * @memberof CreateTribeRequestBody
     * @example 1
     */
    episodeStarted: number;

    /**
     * The tribe's color
     *
     * @type {string}
     * @memberof CreateTribeRequestBody
     * @example #FF0000
     */
    color: string;
}
