/* tslint:disable */
/* eslint-disable */
/**
 * Survivor Fantasy League - OpenAPI 3.0.3
 * This is the Survivor Fantasy League Spec for API's
 *
 * OpenAPI spec version: 1.0.11
 * Contact: pklein111697@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TribeMembersState } from './tribe-members-state';
 /**
 * 
 *
 * @export
 * @interface EpisodeEvents
 */
export interface EpisodeEvents {

    /**
     * Whether the episode is a tribe switch episode
     *
     * @type {boolean}
     * @memberof EpisodeEvents
     * @example false
     */
    isTribeSwitch: boolean;

    /**
     * The tribes in the episode - a map from the tribeId to the tribe
     *
     * @type {{ [key: string]: TribeMembersState; }}
     * @memberof EpisodeEvents
     */
    tribesState: { [key: string]: TribeMembersState; };
}
