/* tslint:disable */
/* eslint-disable */
/**
 * Survivor Fantasy League - OpenAPI 3.0.3
 * This is the Survivor Fantasy League Spec for API's
 *
 * OpenAPI spec version: 1.0.11
 * Contact: pklein111697@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { League } from './league';
import { Profile } from './profile';
 /**
 * 
 *
 * @export
 * @interface LeagueInvite
 */
export interface LeagueInvite {

    /**
     * @type {League}
     * @memberof LeagueInvite
     */
    league?: League;

    /**
     * A message indicating the success of the operation.
     *
     * @type {string}
     * @memberof LeagueInvite
     * @example Tony Stark has invited you to join a league
     */
    message?: string;

    /**
     * @type {Profile}
     * @memberof LeagueInvite
     */
    inviterProfile?: Profile;
}
