/* tslint:disable */
/* eslint-disable */
/**
 * Survivor Fantasy League - OpenAPI 3.0.3
 * This is the Survivor Fantasy League Spec for API's
 *
 * OpenAPI spec version: 1.0.11
 * Contact: pklein111697@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { LeagueMemberRole } from './league-member-role';
import { Profile } from './profile';
 /**
 * 
 *
 * @export
 * @interface LeagueMember
 */
export interface LeagueMember {

    /**
     * @type {Profile}
     * @memberof LeagueMember
     */
    profile: Profile;

    /**
     * @type {LeagueMemberRole}
     * @memberof LeagueMember
     */
    role: LeagueMemberRole;

    /**
     * The id of the league profile
     *
     * @type {string}
     * @memberof LeagueMember
     * @example 5f4e1e1f-4b7b-4b7b-8b7b-4b7b4b7b4b7b
     */
    leagueProfileId: string;

    /**
     * Whether the user has joined the league
     *
     * @type {boolean}
     * @memberof LeagueMember
     * @example true
     */
    hasJoined: boolean;
}
