/* tslint:disable */
/* eslint-disable */
/**
 * Survivor Fantasy League - OpenAPI 3.0.3
 * This is the Survivor Fantasy League Spec for API's
 *
 * OpenAPI spec version: 1.0.11
 * Contact: pklein111697@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Episode } from './episode';
import { Pick } from './pick';
import { SurveyAvailabilityStatusEnum } from './survey-availability-status-enum';
import { SurveySubmissionStatusEnum } from './survey-submission-status-enum';
import { SurveyType } from './survey-type';
 /**
 * 
 *
 * @export
 * @interface LeagueSurvey
 */
export interface LeagueSurvey {

    /**
     * The ID of the league survey
     *
     * @type {string}
     * @memberof LeagueSurvey
     */
    leagueSurveyId: string;

    /**
     * The ID of the survey
     *
     * @type {string}
     * @memberof LeagueSurvey
     * @example 49e27bd8-dc24-4159-9630-e989025bf8fd
     */
    surveyId: string;

    /**
     * @type {Episode}
     * @memberof LeagueSurvey
     */
    episode: Episode;

    /**
     * @type {SurveyType}
     * @memberof LeagueSurvey
     */
    surveyType: SurveyType;

    /**
     * @type {Array<Pick>}
     * @memberof LeagueSurvey
     */
    picks: Array<Pick>;

    /**
     * @type {SurveySubmissionStatusEnum}
     * @memberof LeagueSurvey
     */
    surveySubmissionStatus?: SurveySubmissionStatusEnum;

    /**
     * @type {SurveyAvailabilityStatusEnum}
     * @memberof LeagueSurvey
     */
    surveyAvailabilityStatus?: SurveyAvailabilityStatusEnum;
}
