/* tslint:disable */
/* eslint-disable */
/**
 * Survivor Fantasy League - OpenAPI 3.0.3
 * This is the Survivor Fantasy League Spec for API's
 *
 * OpenAPI spec version: 1.0.11
 * Contact: pklein111697@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Profile } from './profile';
 /**
 * 
 *
 * @export
 * @interface LeagueMember
 */
export interface LeagueMember {

    /**
     * @type {Profile}
     * @memberof LeagueMember
     */
    profile: Profile;

    /**
     * The role of the league member
     *
     * @type {string}
     * @memberof LeagueMember
     * @example member
     */
    role: LeagueMemberRoleEnum;

    /**
     * The id of the league profile
     *
     * @type {string}
     * @memberof LeagueMember
     * @example 5f4e1e1f-4b7b-4b7b-8b7b-4b7b4b7b4b7b
     */
    leagueProfileId: string;
}

/**
 * @export
 * @enum {string}
 */
export enum LeagueMemberRoleEnum {
    OWNER = 'OWNER',
    ADMIN = 'ADMIN',
    MEMBER = 'MEMBER'
}

