/* tslint:disable */
/* eslint-disable */
/**
 * Survivor Fantasy League - OpenAPI 3.0.3
 * This is the Survivor Fantasy League Spec for API's
 *
 * OpenAPI spec version: 1.0.11
 * Contact: pklein111697@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface Pagination
 */
export interface Pagination {

    /**
     * The current page of the result set.
     *
     * @type {number}
     * @memberof Pagination
     * @example 1
     */
    currentPage: number;

    /**
     * The total number of pages available.
     *
     * @type {number}
     * @memberof Pagination
     * @example 1
     */
    totalPages: number;

    /**
     * The total number of profiles that match the search criteria.
     *
     * @type {number}
     * @memberof Pagination
     * @example 8
     */
    totalCount: number;
}
