/* tslint:disable */
/* eslint-disable */
/**
 * Survivor Fantasy League - OpenAPI 3.0.3
 * This is the Survivor Fantasy League Spec for API's
 *
 * OpenAPI spec version: 1.0.11
 * Contact: pklein111697@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BinaryPickOptions } from './binary-pick-options';
import { ColorPickOptions } from './color-pick-options';
import { PickOptionTypeEnum } from './pick-option-type-enum';
import { PickStatusEnum } from './pick-status-enum';
import { SurvivorPickOptions } from './survivor-pick-options';
import { TribePickOptions } from './tribe-pick-options';
 /**
 * 
 *
 * @export
 * @interface Pick
 */
export interface Pick {

    /**
     * The ID of the pick
     *
     * @type {string}
     * @memberof Pick
     * @example 49e27bd8-dc24-4159-9630-e989025bf8fd
     */
    id: string;

    /**
     * The ID of the league profile for this pick
     *
     * @type {string}
     * @memberof Pick
     * @example 49e27bd8-dc24-4159-9630-e989025bf8fd
     */
    leagueProfileId?: string;

    /**
     * The ID of the league the pick belongs to
     *
     * @type {string}
     * @memberof Pick
     * @example 49e27bd8-dc24-4159-9630-e989025bf8fd
     */
    leagueId: string;

    /**
     * The type of survey the pick is for
     *
     * @type {string}
     * @memberof Pick
     * @example Weekly
     */
    surveyType?: PickSurveyTypeEnum;

    /**
     * @type {PickStatusEnum}
     * @memberof Pick
     */
    pickStatus?: PickStatusEnum;

    /**
     * @type {PickOptionTypeEnum}
     * @memberof Pick
     */
    pickOptionType?: PickOptionTypeEnum;

    /**
     * @type {SurvivorPickOptions | ColorPickOptions | TribePickOptions | BinaryPickOptions}
     * @memberof Pick
     */
    pickOptions?: SurvivorPickOptions | ColorPickOptions | TribePickOptions | BinaryPickOptions;
}

/**
 * @export
 * @enum {string}
 */
export enum PickSurveyTypeEnum {
    Weekly = 'Weekly',
    Premier = 'Premier'
}

