/* tslint:disable */
/* eslint-disable */
/**
 * Survivor Fantasy League - OpenAPI 3.0.3
 * This is the Survivor Fantasy League Spec for API's
 *
 * OpenAPI spec version: 1.0.11
 * Contact: pklein111697@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Pick } from './pick';
import { PickChoice } from './pick-choice';
import { PickOptions } from './pick-options';
 /**
 * 
 *
 * @export
 * @interface PickAndChoice
 */
export interface PickAndChoice extends Pick {

    /**
     * @type {PickChoice}
     * @memberof PickAndChoice
     */
    choice: PickChoice;
}
