/* tslint:disable */
/* eslint-disable */
/**
 * Survivor Fantasy League - OpenAPI 3.0.3
 * This is the Survivor Fantasy League Spec for API's
 *
 * OpenAPI spec version: 1.0.11
 * Contact: pklein111697@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { PickOptions } from './pick-options';
import { PlayerChoices } from './player-choices';
 /**
 * 
 *
 * @export
 * @interface Pick
 */
export interface Pick {

    /**
     * The ID of the pick
     *
     * @type {string}
     * @memberof Pick
     */
    id: string;

    /**
     * The description of the pick
     *
     * @type {string}
     * @memberof Pick
     * @example Who will be voted out this week?
     */
    description: string;

    /**
     * The number of points the pick is worth
     *
     * @type {number}
     * @memberof Pick
     * @example 10
     */
    pointValue: number;

    /**
     * @type {PlayerChoices}
     * @memberof Pick
     */
    playerChoices?: PlayerChoices;

    /**
     * @type {PickOptions}
     * @memberof Pick
     */
    options: PickOptions;
}
