/* tslint:disable */
/* eslint-disable */
/**
 * Survivor Fantasy League - OpenAPI 3.0.3
 * This is the Survivor Fantasy League Spec for API's
 *
 * OpenAPI spec version: 1.0.11
 * Contact: pklein111697@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { SurvivorBasic } from './survivor-basic';
 /**
 * 
 *
 * @export
 * @interface Survivor
 */
export interface Survivor extends SurvivorBasic {

    /**
     * The season tied with this survivor's details
     *
     * @type {number}
     * @memberof Survivor
     */
    seasonId: number;

    /**
     * The survivor's nickname
     *
     * @type {string}
     * @memberof Survivor
     * @example The Brain
     */
    nickName?: string | null;

    /**
     * The city the survivor is from
     *
     * @type {string}
     * @memberof Survivor
     * @example Brooklyn
     */
    fromCity?: string | null;

    /**
     * The state the survivor is from
     *
     * @type {string}
     * @memberof Survivor
     * @example New York
     */
    fromState: string;

    /**
     * The country the survivor is from
     *
     * @type {string}
     * @memberof Survivor
     * @example US
     */
    fromCountry: string;

    /**
     * The survivor's age at the time of the season
     *
     * @type {number}
     * @memberof Survivor
     * @example 31
     */
    age: number;

    /**
     * A short description about the survivor
     *
     * @type {string}
     * @memberof Survivor
     * @example An outgoing and energetic person.
     */
    description: string;

    /**
     * The survivor's job/occupation
     *
     * @type {string}
     * @memberof Survivor
     * @example AI Research Assistant
     */
    job: string;

    /**
     * The survivor's first name
     *
     * @type {string}
     * @memberof Survivor
     * @example John
     */
    firstName: string;

    /**
     * The survivor's last name
     *
     * @type {string}
     * @memberof Survivor
     * @example Doe
     */
    lastName: string;
}
