/* tslint:disable */
/* eslint-disable */
/**
 * Survivor Fantasy League - OpenAPI 3.0.3
 * This is the Survivor Fantasy League Spec for API's
 *
 * OpenAPI spec version: 1.0.11
 * Contact: pklein111697@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Episode } from './episode';
import { Pick } from './pick';
import { SurveyType } from './survey-type';
 /**
 * 
 *
 * @export
 * @interface Survey
 */
export interface Survey {

    /**
     * The ID of the survey
     *
     * @type {string}
     * @memberof Survey
     * @example 49e27bd8-dc24-4159-9630-e989025bf8fd
     */
    id?: string;

    /**
     * @type {Episode}
     * @memberof Survey
     */
    episode?: Episode;

    /**
     * @type {SurveyType}
     * @memberof Survey
     */
    surveyType?: SurveyType;

    /**
     * @type {Array<Pick>}
     * @memberof Survey
     */
    picks?: Array<Pick>;
}
