/* tslint:disable */
/* eslint-disable */
/**
 * Survivor Fantasy League - OpenAPI 3.0.3
 * This is the Survivor Fantasy League Spec for API's
 *
 * OpenAPI spec version: 1.0.11
 * Contact: pklein111697@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { SurvivorBasic } from './survivor-basic';
 /**
 * 
 *
 * @export
 * @interface SurvivorWithDetails
 */
export interface SurvivorWithDetails extends SurvivorBasic {

    /**
     * The season tied with this survivor's details
     *
     * @type {number}
     * @memberof SurvivorWithDetails
     */
    seasonId?: number;

    /**
     * The survivor's nickname
     *
     * @type {string}
     * @memberof SurvivorWithDetails
     * @example The Brain
     */
    nickName?: string;

    /**
     * The city the survivor is from
     *
     * @type {string}
     * @memberof SurvivorWithDetails
     * @example Brooklyn
     */
    fromCity?: string;

    /**
     * The state the survivor is from
     *
     * @type {string}
     * @memberof SurvivorWithDetails
     * @example New York
     */
    fromState?: string;

    /**
     * The country the survivor is from
     *
     * @type {string}
     * @memberof SurvivorWithDetails
     * @example US
     */
    fromCountry?: string;

    /**
     * The survivor's age at the time of the season
     *
     * @type {number}
     * @memberof SurvivorWithDetails
     * @example 31
     */
    age?: number;

    /**
     * A short description about the survivor
     *
     * @type {string}
     * @memberof SurvivorWithDetails
     * @example An outgoing and energetic person.
     */
    description?: string;

    /**
     * The survivor's job/occupation
     *
     * @type {string}
     * @memberof SurvivorWithDetails
     * @example AI Research Assistant
     */
    job?: string;

    /**
     * The path of the survivor image
     *
     * @type {string}
     * @memberof SurvivorWithDetails
     * @example /assets/images/survivors/AndyRueda47.jpeg
     */
    imageUrl?: string;
}
