/* tslint:disable */
/* eslint-disable */
/**
 * Survivor Fantasy League - OpenAPI 3.0.3
 * This is the Survivor Fantasy League Spec for API's
 *
 * OpenAPI spec version: 1.0.11
 * Contact: pklein111697@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { SurvivorBasic } from './survivor-basic';
 /**
 * A map where the key is the tribeId and the value contains tribe membership details for the episode
 *
 * @export
 * @interface TribeMembersState
 */
export interface TribeMembersState {

    /**
     * List of member IDs at the start of the episode
     *
     * @type {Array<SurvivorBasic>}
     * @memberof TribeMembersState
     */
    tribeMembersEpisodeStart: Array<SurvivorBasic>;

    /**
     * @type {Array<SurvivorBasic>}
     * @memberof TribeMembersState
     */
    tribeMembersBeforeElimination: Array<SurvivorBasic>;

    /**
     * @type {Array<SurvivorBasic>}
     * @memberof TribeMembersState
     */
    tribeMembersAtEndOfEpisode: Array<SurvivorBasic>;
}
