/* tslint:disable */
/* eslint-disable */
/**
 * Survivor Fantasy League - OpenAPI 3.0.3
 * This is the Survivor Fantasy League Spec for API's
 *
 * OpenAPI spec version: 1.0.11
 * Contact: pklein111697@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Color } from './color';
import { SurvivorBasic } from './survivor-basic';
 /**
 * 
 *
 * @export
 * @interface Tribe
 */
export interface Tribe {

    /**
     * @type {Array<SurvivorBasic>}
     * @memberof Tribe
     */
    survivors: Array<SurvivorBasic>;

    /**
     * The season's unique identifier
     *
     * @type {string}
     * @memberof Tribe
     * @example 47
     */
    seasonId: string;

    /**
     * The tribe's unique identifier
     *
     * @type {string}
     * @memberof Tribe
     */
    id: string;

    /**
     * The tribe's name
     *
     * @type {string}
     * @memberof Tribe
     * @example Luzon
     */
    name: string;

    /**
     * @type {Color}
     * @memberof Tribe
     */
    color: Color;

    /**
     * Whether the tribe is a merge tribe
     *
     * @type {boolean}
     * @memberof Tribe
     * @example false
     */
    isMergeTribe?: boolean;

    /**
     * The id of the episode the tribe started in
     *
     * @type {string}
     * @memberof Tribe
     */
    episodeStarted?: string;
}
