/* tslint:disable */
/* eslint-disable */
/**
 * Survivor Fantasy League - OpenAPI 3.0.3
 * This is the Survivor Fantasy League Spec for API's
 *
 * OpenAPI spec version: 1.0.11
 * Contact: pklein111697@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { GetSurvivorsResponse } from '../models';
/**
 * SurvivorServiceApi - axios parameter creator
 * @export
 */
export const SurvivorServiceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retrieves a list of survivors. Optionally, filter by season ID and request detailed information.
         * @summary Get survivors
         * @param {number} [seasonId] 
         * @param {boolean} [withDetails] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSurvivors: async (seasonId?: number, withDetails?: boolean, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/season/survivors`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (seasonId !== undefined) {
                localVarQueryParameter['seasonId'] = seasonId;
            }

            if (withDetails !== undefined) {
                localVarQueryParameter['withDetails'] = withDetails;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SurvivorServiceApi - functional programming interface
 * @export
 */
export const SurvivorServiceApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Retrieves a list of survivors. Optionally, filter by season ID and request detailed information.
         * @summary Get survivors
         * @param {number} [seasonId] 
         * @param {boolean} [withDetails] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSurvivors(seasonId?: number, withDetails?: boolean, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<GetSurvivorsResponse>>> {
            const localVarAxiosArgs = await SurvivorServiceApiAxiosParamCreator(configuration).getSurvivors(seasonId, withDetails, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * SurvivorServiceApi - factory interface
 * @export
 */
export const SurvivorServiceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Retrieves a list of survivors. Optionally, filter by season ID and request detailed information.
         * @summary Get survivors
         * @param {number} [seasonId] 
         * @param {boolean} [withDetails] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSurvivors(seasonId?: number, withDetails?: boolean, options?: AxiosRequestConfig): Promise<AxiosResponse<GetSurvivorsResponse>> {
            return SurvivorServiceApiFp(configuration).getSurvivors(seasonId, withDetails, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SurvivorServiceApi - object-oriented interface
 * @export
 * @class SurvivorServiceApi
 * @extends {BaseAPI}
 */
export class SurvivorServiceApi extends BaseAPI {
    /**
     * Retrieves a list of survivors. Optionally, filter by season ID and request detailed information.
     * @summary Get survivors
     * @param {number} [seasonId] 
     * @param {boolean} [withDetails] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SurvivorServiceApi
     */
    public async getSurvivors(seasonId?: number, withDetails?: boolean, options?: AxiosRequestConfig) : Promise<AxiosResponse<GetSurvivorsResponse>> {
        return SurvivorServiceApiFp(this.configuration).getSurvivors(seasonId, withDetails, options).then((request) => request(this.axios, this.basePath));
    }
}
