openapi: 3.0.0
info:
  title: Survivor Fantasy League API
  version: 1.0.0
  description: API Documentation for the Survivor Fantasy League application
servers:
  - url: http://localhost:3000  # Adjust this based on your server's URL
paths:
  /api/auth/signup:
    post:
      summary: Register a new user
      description: Creates a new User account with a provided email, username, and password.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - username
              properties:
                email:
                  type: string
                  example: user@example.com
                password:
                  type: string
                  example: StrongPassword123
                username:
                  type: string
                  example: SurvivorFan69
      responses:
        '201':
          description: User created successfully
        '400':
          description: Bad request
        '500':
          description: Internal Server Error

  /api/auth/login:
    post:
      summary: Log in a user
      description: Authenticates a user with email and password.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  example: user@example.com
                password:
                  type: string
                  example: StrongPassword123
      responses:
        '200':
          description: User authenticated successfully
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error