openapi: "3.0.3"
info:
  title: "Survivor Fantasy League - OpenAPI 3.0.3"
  description: "This is the Survivor Fantasy League Spec for API's"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "pklein111697@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  version: "1.0.11"
servers:
  - url: "http://localhost:3000"
    variables: {}
paths:
  /api/profile/leagueInvite:
    $ref: "./paths/profile/leagueInvite.yaml#/paths/leagueInvite"

components:
  securitySchemes:
    accessTokenCookie:
      type: apiKey
      in: cookie
      name: accessToken
      description: JWT token for authentication.
    refreshTokenCookie:
      type: apiKey
      in: cookie
      name: refreshToken
      description: JWT token used to refresh access tokens.
