openapi: '3.0.3'
info:
  title: 'Survivor Fantasy League - OpenAPI 3.0.3'
  description: "This is the Survivor Fantasy League Spec for API's"
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: 'pklein111697@gmail.com'
  license:
    name: 'Apache 2.0'
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: '1.0.11'
servers:
  - url: 'http://localhost:3000'
  - url: 'http://134.199.141.129:3000'
    variables: {}
paths:
  /api/auth/signup:
    $ref: './paths/auth/signup.yaml#/paths/signup'
  /api/auth/login:
    $ref: './paths/auth/login.yaml#/paths/login'
  /api/auth/logout:
    $ref: './paths/auth/logout.yaml#/paths/logout'
  /api/auth/extend-session:
    $ref: './paths/auth/extendSession.yaml#/paths/extendSession'
  /api/auth/check-auth:
    $ref: './paths/auth/checkAuth.yaml#/paths/checkAuth'

  /api/season:
    $ref: './paths/season/season.yaml#/paths/season'

  /api/league/{profileId}/{seasonId}:
    $ref: './paths/league/league.yaml#/paths/league'
  /api/league/invite/{profileId}/{seasonId}:
    $ref: './paths/league/invite/invite.yaml#/paths/leagueInvite'
  /api/league/invite/search:
    $ref: './paths/league/invite/search/search.yaml#/paths/search'

  /api/league/survey/{leagueId}/{profileId}:
    $ref: './paths/league/survey/survey.yaml#/paths/surveys'
  /api/league/survey/{leagueId}/{profileId}/{episodeId}:
    $ref: './paths/league/survey/survey.yaml#/paths/survey'
  /api/league/survey/submit:
    $ref: './paths/league/survey/survey.yaml#/paths/submitSurvey'

  /api/image/profile/{profileId}:
    $ref: './paths/image/profile.yaml#/paths/profileImage'
  /api/image/league/{leagueId}:
    $ref: './paths/image/league.yaml#/paths/leagueImage'
  /api/image/season/{seasonId}:
    $ref: './paths/image/season.yaml#/paths/seasonLogoImage'
  /api/image/episode/{episodeId}:
    $ref: './paths/image/episode.yaml#/paths/episodeImage'
  /api/image/survivor/{seasonId}/{survivorId}:
    $ref: './paths/image/survivor.yaml#/paths/survivorImage'
  /api/image/tribe/{seasonId}/{tribeId}:
    $ref: './paths/image/tribe.yaml#/paths/tribeImage'

  /api/admin/season:
    $ref: './paths/admin/season/season.yaml#/paths/season'
  /api/admin/season/survivor:
    $ref: './paths/admin/season/survivor/survivor.yaml#/paths/survivor'
  /api/admin/season/tribe:
    $ref: './paths/admin/season/tribe/tribe.yaml#/paths/tribe'

  /api/admin/season/events/{episodeId}/elimination:
    $ref: './paths/admin/season/events/elimination.yaml#/paths/elimination'

components:
  securitySchemes:
    accessTokenCookie:
      type: apiKey
      in: cookie
      name: accessToken
      description: JWT token for authentication.
    refreshTokenCookie:
      type: apiKey
      in: cookie
      name: refreshToken
      description: JWT token used to refresh access tokens.
