openapi: "3.0.3"
info:
  title: "Survivor Fantasy League - OpenAPI 3.0.3"
  description: "This is the Survivor Fantasy League Spec for API's"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "pklein111697@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  version: "1.0.11"
servers:
  - url: "http://localhost:3000"
    variables: {}
paths:
  /api/auth/signup:
    $ref: "./paths/authPaths.yaml#/Signup"
  /api/auth/login:
    $ref: "./paths/authPaths.yaml#/Login"
  /api/auth/logout:
    $ref: "./paths/authPaths.yaml#/Logout"
  /api/auth/check-auth:
    $ref: "./paths/tokenPaths.yaml#/CheckAuth"
  /api/auth/extend-session:
    $ref: "./paths/tokenPaths.yaml#/ExtendSession"
  /api/profile/leagues:
    $ref: "./paths/profilePaths/profileLeaguesPaths.yaml#/ProfileLeagues"
  /api/survivor:
    $ref: "./paths/survivorPaths.yaml#/Survivors"
  /api/league/profile/search:
    $ref: "./paths/leaguePaths/leagueProfilesPaths.yaml#/ProfileSearchForLeagueInvite"
  /api/league/profile/invite:
    $ref: "./paths/leaguePaths/leagueProfilesPaths.yaml#/InviteProfileToLeague"
  # /api/notification/{notificationId}:
  #   $ref: "./paths/notificationPaths.yaml#/MarkNotificationAsRead"
components:
  schemas:
    Errors:
      type: object
      properties:
        ApiError:
          $ref: "./components/errorComponents.yaml#/components/schemas/ApiError"
        BadRequestError:
          $ref: "./components/errorComponents.yaml#/components/schemas/BadRequestError"
        NotFoundError:
          $ref: "./components/errorComponents.yaml#/components/schemas/NotFoundError"
        ConflictError:
          $ref: "./components/errorComponents.yaml#/components/schemas/ConflictError"
        UnauthorizedError:
          $ref: "./components/errorComponents.yaml#/components/schemas/UnauthorizedError"
        ForbiddenError:
          $ref: "./components/errorComponents.yaml#/components/schemas/ForbiddenError"
        InternalServerError:
          $ref: "./components/errorComponents.yaml#/components/schemas/InternalServerError"
    Account:
      $ref: "./components/authComponents.yaml#/components/schemas/Account"

    UserSessionResponseSuccess:
      $ref: "./components/authComponents.yaml#/components/responses/UserCreateSessionResponseSuccess"
    LogoutSuccessResponseSchema:
      $ref: "./components/authComponents.yaml#/components/responses/LogoutUserResponseSuccess"

  securitySchemes:
    accessTokenCookie:
      type: apiKey
      in: cookie
      name: accessToken
      description: JWT token for authentication.
    refreshTokenCookie:
      type: apiKey
      in: cookie
      name: refreshToken
      description: JWT token used to refresh access tokens.
