/* tslint:disable */
/* eslint-disable */
/**
 * Survivor Fantasy League - OpenAPI 3.0.3
 * This is the Survivor Fantasy League Spec for API's
 *
 * OpenAPI spec version: 1.0.11
 * Contact: pklein111697@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { ProcessEliminationRequestBody } from '../models';
import { ProcessEliminationResponse } from '../models';
/**
 * AdminEventSurviceApi - axios parameter creator
 * @export
 */
export const AdminEventSurviceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * This endpoint allows you to fulfill an elimination survey.
         * @summary Fulfill elimination survey
         * @param {ProcessEliminationRequestBody} body 
         * @param {string} episodeId The id of the episode the event was fulfilled on.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        processElimination: async (body: ProcessEliminationRequestBody, episodeId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling processElimination.');
            }
            // verify required parameter 'episodeId' is not null or undefined
            if (episodeId === null || episodeId === undefined) {
                throw new RequiredError('episodeId','Required parameter episodeId was null or undefined when calling processElimination.');
            }
            const localVarPath = `/api/admin/season/events/{episodeId}/elimination`
                .replace(`{${"episodeId"}}`, encodeURIComponent(String(episodeId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AdminEventSurviceApi - functional programming interface
 * @export
 */
export const AdminEventSurviceApiFp = function(configuration?: Configuration) {
    return {
        /**
         * This endpoint allows you to fulfill an elimination survey.
         * @summary Fulfill elimination survey
         * @param {ProcessEliminationRequestBody} body 
         * @param {string} episodeId The id of the episode the event was fulfilled on.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async processElimination(body: ProcessEliminationRequestBody, episodeId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<ProcessEliminationResponse>>> {
            const localVarAxiosArgs = await AdminEventSurviceApiAxiosParamCreator(configuration).processElimination(body, episodeId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * AdminEventSurviceApi - factory interface
 * @export
 */
export const AdminEventSurviceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * This endpoint allows you to fulfill an elimination survey.
         * @summary Fulfill elimination survey
         * @param {ProcessEliminationRequestBody} body 
         * @param {string} episodeId The id of the episode the event was fulfilled on.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async processElimination(body: ProcessEliminationRequestBody, episodeId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<ProcessEliminationResponse>> {
            return AdminEventSurviceApiFp(configuration).processElimination(body, episodeId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AdminEventSurviceApi - object-oriented interface
 * @export
 * @class AdminEventSurviceApi
 * @extends {BaseAPI}
 */
export class AdminEventSurviceApi extends BaseAPI {
    /**
     * This endpoint allows you to fulfill an elimination survey.
     * @summary Fulfill elimination survey
     * @param {ProcessEliminationRequestBody} body 
     * @param {string} episodeId The id of the episode the event was fulfilled on.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminEventSurviceApi
     */
    public async processElimination(body: ProcessEliminationRequestBody, episodeId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<ProcessEliminationResponse>> {
        return AdminEventSurviceApiFp(this.configuration).processElimination(body, episodeId, options).then((request) => request(this.axios, this.basePath));
    }
}
