/* tslint:disable */
/* eslint-disable */
/**
 * Survivor Fantasy League - OpenAPI 3.0.3
 * This is the Survivor Fantasy League Spec for API's
 *
 * OpenAPI spec version: 1.0.11
 * Contact: pklein111697@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { GetCurrentEpisodSurveysResponse } from '../models';
/**
 * LeagueApi - axios parameter creator
 * @export
 */
export const LeagueApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get all outstanding open surveys for the current user. 
         * @summary Get all outstanding open surveys
         * @param {string} profileId The ID of the profile.
         * @param {Array<string>} leagueIds The ID of the league.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCurrentEpisodeSurveys: async (profileId: string, leagueIds: Array<string>, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'profileId' is not null or undefined
            if (profileId === null || profileId === undefined) {
                throw new RequiredError('profileId','Required parameter profileId was null or undefined when calling getCurrentEpisodeSurveys.');
            }
            // verify required parameter 'leagueIds' is not null or undefined
            if (leagueIds === null || leagueIds === undefined) {
                throw new RequiredError('leagueIds','Required parameter leagueIds was null or undefined when calling getCurrentEpisodeSurveys.');
            }
            const localVarPath = `/api/league/currentEpisodeSurveys/{profileId}/{leagueIds}`
                .replace(`{${"profileId"}}`, encodeURIComponent(String(profileId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication accessTokenCookie required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("accessToken")
                    : await configuration.apiKey;
                localVarQueryParameter["accessToken"] = localVarApiKeyValue;
            }

            if (leagueIds) {
                localVarQueryParameter['leagueIds'] = leagueIds;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * LeagueApi - functional programming interface
 * @export
 */
export const LeagueApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Get all outstanding open surveys for the current user. 
         * @summary Get all outstanding open surveys
         * @param {string} profileId The ID of the profile.
         * @param {Array<string>} leagueIds The ID of the league.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCurrentEpisodeSurveys(profileId: string, leagueIds: Array<string>, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<GetCurrentEpisodSurveysResponse>>> {
            const localVarAxiosArgs = await LeagueApiAxiosParamCreator(configuration).getCurrentEpisodeSurveys(profileId, leagueIds, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * LeagueApi - factory interface
 * @export
 */
export const LeagueApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Get all outstanding open surveys for the current user. 
         * @summary Get all outstanding open surveys
         * @param {string} profileId The ID of the profile.
         * @param {Array<string>} leagueIds The ID of the league.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCurrentEpisodeSurveys(profileId: string, leagueIds: Array<string>, options?: AxiosRequestConfig): Promise<AxiosResponse<GetCurrentEpisodSurveysResponse>> {
            return LeagueApiFp(configuration).getCurrentEpisodeSurveys(profileId, leagueIds, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * LeagueApi - object-oriented interface
 * @export
 * @class LeagueApi
 * @extends {BaseAPI}
 */
export class LeagueApi extends BaseAPI {
    /**
     * Get all outstanding open surveys for the current user. 
     * @summary Get all outstanding open surveys
     * @param {string} profileId The ID of the profile.
     * @param {Array<string>} leagueIds The ID of the league.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LeagueApi
     */
    public async getCurrentEpisodeSurveys(profileId: string, leagueIds: Array<string>, options?: AxiosRequestConfig) : Promise<AxiosResponse<GetCurrentEpisodSurveysResponse>> {
        return LeagueApiFp(this.configuration).getCurrentEpisodeSurveys(profileId, leagueIds, options).then((request) => request(this.axios, this.basePath));
    }
}
