/* tslint:disable */
/* eslint-disable */
/**
 * Survivor Fantasy League - OpenAPI 3.0.3
 * This is the Survivor Fantasy League Spec for API's
 *
 * OpenAPI spec version: 1.0.11
 * Contact: pklein111697@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { GetLeagueMemberSurveyResponse } from '../models';
import { GetLeagueMemberSurveysResponse } from '../models';
import { SubmitSurveyRequestBody } from '../models';
import { SubmitSurveyResponse } from '../models';
/**
 * SurveyServiceApi - axios parameter creator
 * @export
 */
export const SurveyServiceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get survey for profileId, and episodeId with optional leagueId
         * @param {string} leagueId 
         * @param {string} profileId 
         * @param {string} episodeId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLeagueSurvey: async (leagueId: string, profileId: string, episodeId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'leagueId' is not null or undefined
            if (leagueId === null || leagueId === undefined) {
                throw new RequiredError('leagueId','Required parameter leagueId was null or undefined when calling getLeagueSurvey.');
            }
            // verify required parameter 'profileId' is not null or undefined
            if (profileId === null || profileId === undefined) {
                throw new RequiredError('profileId','Required parameter profileId was null or undefined when calling getLeagueSurvey.');
            }
            // verify required parameter 'episodeId' is not null or undefined
            if (episodeId === null || episodeId === undefined) {
                throw new RequiredError('episodeId','Required parameter episodeId was null or undefined when calling getLeagueSurvey.');
            }
            const localVarPath = `/api/league/survey/{leagueId}/{profileId}/{episodeId}`
                .replace(`{${"leagueId"}}`, encodeURIComponent(String(leagueId)))
                .replace(`{${"profileId"}}`, encodeURIComponent(String(profileId)))
                .replace(`{${"episodeId"}}`, encodeURIComponent(String(episodeId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Gets all surveys for the specified profileId and leagueId (mainly used to get all statuses of the leagueSurveys)
         * @summary Get all Surveys for profiledId and leagueId,
         * @param {string} leagueId 
         * @param {string} profileId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLeagueSurveys: async (leagueId: string, profileId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'leagueId' is not null or undefined
            if (leagueId === null || leagueId === undefined) {
                throw new RequiredError('leagueId','Required parameter leagueId was null or undefined when calling getLeagueSurveys.');
            }
            // verify required parameter 'profileId' is not null or undefined
            if (profileId === null || profileId === undefined) {
                throw new RequiredError('profileId','Required parameter profileId was null or undefined when calling getLeagueSurveys.');
            }
            const localVarPath = `/api/league/survey/{leagueId}/{profileId}`
                .replace(`{${"leagueId"}}`, encodeURIComponent(String(leagueId)))
                .replace(`{${"profileId"}}`, encodeURIComponent(String(profileId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Submits the survey for the specified profileId's in leagueId for episodeId's
         * @summary Submit survey for provided episodeId and profileId
         * @param {SubmitSurveyRequestBody} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        submitSurveyWithPickChoices: async (body: SubmitSurveyRequestBody, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling submitSurveyWithPickChoices.');
            }
            const localVarPath = `/api/league/survey/submit`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SurveyServiceApi - functional programming interface
 * @export
 */
export const SurveyServiceApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get survey for profileId, and episodeId with optional leagueId
         * @param {string} leagueId 
         * @param {string} profileId 
         * @param {string} episodeId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getLeagueSurvey(leagueId: string, profileId: string, episodeId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<GetLeagueMemberSurveyResponse>>> {
            const localVarAxiosArgs = await SurveyServiceApiAxiosParamCreator(configuration).getLeagueSurvey(leagueId, profileId, episodeId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Gets all surveys for the specified profileId and leagueId (mainly used to get all statuses of the leagueSurveys)
         * @summary Get all Surveys for profiledId and leagueId,
         * @param {string} leagueId 
         * @param {string} profileId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getLeagueSurveys(leagueId: string, profileId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<GetLeagueMemberSurveysResponse>>> {
            const localVarAxiosArgs = await SurveyServiceApiAxiosParamCreator(configuration).getLeagueSurveys(leagueId, profileId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Submits the survey for the specified profileId's in leagueId for episodeId's
         * @summary Submit survey for provided episodeId and profileId
         * @param {SubmitSurveyRequestBody} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async submitSurveyWithPickChoices(body: SubmitSurveyRequestBody, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<SubmitSurveyResponse>>> {
            const localVarAxiosArgs = await SurveyServiceApiAxiosParamCreator(configuration).submitSurveyWithPickChoices(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * SurveyServiceApi - factory interface
 * @export
 */
export const SurveyServiceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Get survey for profileId, and episodeId with optional leagueId
         * @param {string} leagueId 
         * @param {string} profileId 
         * @param {string} episodeId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getLeagueSurvey(leagueId: string, profileId: string, episodeId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<GetLeagueMemberSurveyResponse>> {
            return SurveyServiceApiFp(configuration).getLeagueSurvey(leagueId, profileId, episodeId, options).then((request) => request(axios, basePath));
        },
        /**
         * Gets all surveys for the specified profileId and leagueId (mainly used to get all statuses of the leagueSurveys)
         * @summary Get all Surveys for profiledId and leagueId,
         * @param {string} leagueId 
         * @param {string} profileId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getLeagueSurveys(leagueId: string, profileId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<GetLeagueMemberSurveysResponse>> {
            return SurveyServiceApiFp(configuration).getLeagueSurveys(leagueId, profileId, options).then((request) => request(axios, basePath));
        },
        /**
         * Submits the survey for the specified profileId's in leagueId for episodeId's
         * @summary Submit survey for provided episodeId and profileId
         * @param {SubmitSurveyRequestBody} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async submitSurveyWithPickChoices(body: SubmitSurveyRequestBody, options?: AxiosRequestConfig): Promise<AxiosResponse<SubmitSurveyResponse>> {
            return SurveyServiceApiFp(configuration).submitSurveyWithPickChoices(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SurveyServiceApi - object-oriented interface
 * @export
 * @class SurveyServiceApi
 * @extends {BaseAPI}
 */
export class SurveyServiceApi extends BaseAPI {
    /**
     * 
     * @summary Get survey for profileId, and episodeId with optional leagueId
     * @param {string} leagueId 
     * @param {string} profileId 
     * @param {string} episodeId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SurveyServiceApi
     */
    public async getLeagueSurvey(leagueId: string, profileId: string, episodeId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<GetLeagueMemberSurveyResponse>> {
        return SurveyServiceApiFp(this.configuration).getLeagueSurvey(leagueId, profileId, episodeId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Gets all surveys for the specified profileId and leagueId (mainly used to get all statuses of the leagueSurveys)
     * @summary Get all Surveys for profiledId and leagueId,
     * @param {string} leagueId 
     * @param {string} profileId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SurveyServiceApi
     */
    public async getLeagueSurveys(leagueId: string, profileId: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<GetLeagueMemberSurveysResponse>> {
        return SurveyServiceApiFp(this.configuration).getLeagueSurveys(leagueId, profileId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Submits the survey for the specified profileId's in leagueId for episodeId's
     * @summary Submit survey for provided episodeId and profileId
     * @param {SubmitSurveyRequestBody} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SurveyServiceApi
     */
    public async submitSurveyWithPickChoices(body: SubmitSurveyRequestBody, options?: AxiosRequestConfig) : Promise<AxiosResponse<SubmitSurveyResponse>> {
        return SurveyServiceApiFp(this.configuration).submitSurveyWithPickChoices(body, options).then((request) => request(this.axios, this.basePath));
    }
}
