/* tslint:disable */
/* eslint-disable */
/**
 * Survivor Fantasy League - OpenAPI 3.0.3
 * This is the Survivor Fantasy League Spec for API's
 *
 * OpenAPI spec version: 1.0.11
 * Contact: pklein111697@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { CreateTribeRequestBody } from '../models';
import { CreateTribeResponse } from '../models';
/**
 * TribeServiceApi - axios parameter creator
 * @export
 */
export const TribeServiceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Creates a new tribe for a given season.
         * @summary Create a new tribe
         * @param {CreateTribeRequestBody} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTribe: async (body: CreateTribeRequestBody, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling createTribe.');
            }
            const localVarPath = `/api/admin/season/tribe`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication accessTokenCookie required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("accessToken")
                    : await configuration.apiKey;
                localVarQueryParameter["accessToken"] = localVarApiKeyValue;
            }

            // authentication refreshTokenCookie required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("refreshToken")
                    : await configuration.apiKey;
                localVarQueryParameter["refreshToken"] = localVarApiKeyValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TribeServiceApi - functional programming interface
 * @export
 */
export const TribeServiceApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Creates a new tribe for a given season.
         * @summary Create a new tribe
         * @param {CreateTribeRequestBody} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createTribe(body: CreateTribeRequestBody, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<CreateTribeResponse>>> {
            const localVarAxiosArgs = await TribeServiceApiAxiosParamCreator(configuration).createTribe(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * TribeServiceApi - factory interface
 * @export
 */
export const TribeServiceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Creates a new tribe for a given season.
         * @summary Create a new tribe
         * @param {CreateTribeRequestBody} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createTribe(body: CreateTribeRequestBody, options?: AxiosRequestConfig): Promise<AxiosResponse<CreateTribeResponse>> {
            return TribeServiceApiFp(configuration).createTribe(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TribeServiceApi - object-oriented interface
 * @export
 * @class TribeServiceApi
 * @extends {BaseAPI}
 */
export class TribeServiceApi extends BaseAPI {
    /**
     * Creates a new tribe for a given season.
     * @summary Create a new tribe
     * @param {CreateTribeRequestBody} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TribeServiceApi
     */
    public async createTribe(body: CreateTribeRequestBody, options?: AxiosRequestConfig) : Promise<AxiosResponse<CreateTribeResponse>> {
        return TribeServiceApiFp(this.configuration).createTribe(body, options).then((request) => request(this.axios, this.basePath));
    }
}
