openapi: 3.0.3
info:
  title: Survivor Fantasy League - OpenAPI 3.0.3
  description: This is the Survivor Fantasy League Spec for API's
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: pklein111697@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.0.11
servers:
  - url: 'http://localhost:3000'
    variables: {}
paths:
  /api/league/profile/invite:
    get:
      summary: Retrieve league invites for a profile
      description: This endpoint allows you to retrieve league invites for a profile. The profile must have a valid token and profileId query parameters.
      operationId: getLeagueInvites
      tags:
        - League
      parameters:
        - name: profileId
          in: query
          required: true
          description: The ID of the profile.
          schema:
            type: string
      responses:
        '200':
          description: A list of league invites for the profile
          content:
            application/json:
              schema:
                type: object
                allOf:
                  - type: object
                    properties:
                      success:
                        type: boolean
                        example: true
                      message:
                        type: string
                        example: Operation completed successfully.
                      statusCode:
                        type: integer
                        example: 200
                      error:
                        type: string
                        nullable: true
                        example: An error occurred.
                  - type: object
                    properties:
                      responseData:
                        type: object
                        properties:
                          leagueInvites:
                            type: array
                            items:
                              type: object
                              properties:
                                league:
                                  type: object
                                  properties:
                                    leagueId:
                                      type: string
                                      description: The ID of the league.
                                      example: c5ea9a19-c8cd-4dfc-af1b-44d3b0d4928f
                                    name:
                                      type: string
                                      description: The name of the league.
                                      example: Corner By The Bookshelf
                                    season:
                                      type: string
                                      description: The season the league belongs to.
                                      example: 47
                                message:
                                  type: string
                                  description: A message indicating the success of the operation.
                                  example: Tony Stark has invited you to join a league
                                inviterProfile:
                                  type: object
                                  properties:
                                    profileId:
                                      type: string
                                    username:
                                      type: string
                                    firstName:
                                      type: string
                                    lastName:
                                      type: string
                                    profileImageUrl:
                                      type: string
                          numLeagueInvites:
                            type: integer
                            description: The number of league invites returned
                            example: 4
              examples:
                success:
                  summary: League invites successfully retrieved
                  value:
                    success: true
                    message: League invites successfully retrieved.
                    responseData:
                      leagueInvites:
                        - leagueId: c5ea9a19-c8cd-4dfc-af1b-44d3b0d4928f
                          name: Corner By The Bookshelf
                          season: 47
                      numLeagueInvites: 4
                    statusCode: 200
      security:
        - accessTokenCookie: []
        - refreshTokenCookie: []
components:
  schemas:
    ApiResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
          example: Operation completed successfully.
        statusCode:
          type: integer
          example: 200
        error:
          type: string
          nullable: true
          example: An error occurred.
    GetLeagueInvitesResponseData:
      type: object
      properties:
        leagueInvites:
          type: array
          items:
            type: object
            properties:
              league:
                type: object
                properties:
                  leagueId:
                    type: string
                    description: The ID of the league.
                    example: c5ea9a19-c8cd-4dfc-af1b-44d3b0d4928f
                  name:
                    type: string
                    description: The name of the league.
                    example: Corner By The Bookshelf
                  season:
                    type: string
                    description: The season the league belongs to.
                    example: 47
              message:
                type: string
                description: A message indicating the success of the operation.
                example: Tony Stark has invited you to join a league
              inviterProfile:
                type: object
                properties:
                  profileId:
                    type: string
                  username:
                    type: string
                  firstName:
                    type: string
                  lastName:
                    type: string
                  profileImageUrl:
                    type: string
        numLeagueInvites:
          type: integer
          description: The number of league invites returned
          example: 4
    GetLeagueInvitesResponse:
      type: object
      allOf:
        - type: object
          properties:
            success:
              type: boolean
              example: true
            message:
              type: string
              example: Operation completed successfully.
            statusCode:
              type: integer
              example: 200
            error:
              type: string
              nullable: true
              example: An error occurred.
        - type: object
          properties:
            responseData:
              type: object
              properties:
                leagueInvites:
                  type: array
                  items:
                    type: object
                    properties:
                      league:
                        type: object
                        properties:
                          leagueId:
                            type: string
                            description: The ID of the league.
                            example: c5ea9a19-c8cd-4dfc-af1b-44d3b0d4928f
                          name:
                            type: string
                            description: The name of the league.
                            example: Corner By The Bookshelf
                          season:
                            type: string
                            description: The season the league belongs to.
                            example: 47
                      message:
                        type: string
                        description: A message indicating the success of the operation.
                        example: Tony Stark has invited you to join a league
                      inviterProfile:
                        type: object
                        properties:
                          profileId:
                            type: string
                          username:
                            type: string
                          firstName:
                            type: string
                          lastName:
                            type: string
                          profileImageUrl:
                            type: string
                numLeagueInvites:
                  type: integer
                  description: The number of league invites returned
                  example: 4
    League:
      type: object
      properties:
        leagueId:
          type: string
          description: The ID of the league.
          example: c5ea9a19-c8cd-4dfc-af1b-44d3b0d4928f
        name:
          type: string
          description: The name of the league.
          example: Corner By The Bookshelf
        season:
          type: string
          description: The season the league belongs to.
          example: 47
    Profile:
      type: object
      properties:
        profileId:
          type: string
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        profileImageUrl:
          type: string
  securitySchemes:
    accessTokenCookie:
      type: apiKey
      in: cookie
      name: accessToken
      description: JWT token for authentication.
    refreshTokenCookie:
      type: apiKey
      in: cookie
      name: refreshToken
      description: JWT token used to refresh access tokens.
